<?xml version="1.0"?>
<robot name="diff_robot" xmlns:xacro="http://www.ros.org/wiki/xacro"> <!--Ak nebude fungovat skusit tu vlozit tu xmls stranku -->


<material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
</material>

<material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
</material>

<material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
</material>




<!-- urobit properties aj na jointy-->
<xacro:property name="base_radius" value="0.2"/>
<xacro:property name="base_length" value="0.03"/>
<xacro:property name="base_mass"   value="5"/>


<xacro:property name="PI_2"         value="1.57079632679"/>
<xacro:property name="wheel_radius" value="0.075"/>
<xacro:property name="wheel_length" value="0.02"/>
<xacro:property name="wheel_mass"   value="1.5"/>


<xacro:property name="caster_radius" value="0.03"/>
<xacro:property name="caster_mass"   value="0.2"/>

<xacro:property name="sensor_size" value="0.05"/> <!-- pozriet rozmery-->

<xacro:property name="camera_size" value="0.05"/> <!-- pozriet rozmery-->

<xacro:macro name="cylinder_inertia"        params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                  izz="${m*r*r/2}" />
</xacro:macro>
<xacro:macro name="sphere_inertia"   params="m r">
    <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                  iyy="${2*m*r*r/5}" iyz = "0"
                  izz="${2*m*r*r/5}" />
</xacro:macro>

<!-- BASE FOOTPRINT-->
 <link name="base_footprint">
 <visual>
 <origin rpy="0 0 0" xyz="0 0 0"/>
 <geometry>
 <box size="0.001 0.001 0.001"/>
 </geometry>
 </visual>
 </link>

<joint name="base_footprint_joint" type="fixed">
 <origin rpy="0 0 0" xyz="0 0 ${wheel_radius}"/>
 <parent link="base_footprint"/>
 <child link="base_link"/>
 </joint>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

<!-- BASE-->
<link name="base_link">
    <visual>
        <geometry>
            <cylinder length="${base_length}" radius="${base_radius}"/>
        </geometry>

        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="Blue"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${base_length}" radius="${base_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
        <mass value="${base_mass}"/>
        <origin xyz="0 0 0"/>
            <!--3x3 rotacna zotrvacna matica, Ak je symetricka staci 6 elementov -->
        <cylinder_inertia  m="${base_mass}" r="${base_radius}" h="${base_length}" />
    </inertial>
</link>
<gazebo reference="base_link">
    <turnGravityOff>false</turnGravityOff>
    <material>Gazebo/Blue</material>

</gazebo>


<!-- LEFT-->
<link name="left_wheel_link">
    <visual>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>

        <origin rpy="${PI_2} 0 0" xyz="0 0 0"/> <!-- 1.5 otoci koleso aby "stalo", xyz posuva na poziciu -->
        <material name="Black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="${PI_2} 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
        <mass value="${wheel_mass}"/>  <!-- preco take tazke???-->
        <origin xyz="0 0 0"/>
            <!--3x3 rotacna zotrvacna matica, Ak je symetricka staci 6 elementov -->
        <cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
    </inertial>
</link>
<gazebo reference="left_wheel_link">
    <turnGravityOff>false</turnGravityOff>
    <material>Gazebo/Black</material>
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
    <fdir1 value="1 0 0"/>

</gazebo>


<joint name="left_wheel_joint" type="continuous">  <!--CONTINUOUS- aby sa neobmedzene otacal -->
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin rpy="0 0 0" xyz="0 -0.2 0"/>                              <!-- Ake hodnoty?-->
    <axis xyz="0 1 0" rpy="0  0"/>                               <!-- Povoli rotaciu okolo osi X-->
    <limit effort="100" velocity="100" />  <!-- pre Joint State PUblisher, HODNOTY??? -->
    <dynamics damping="0.0" friction="0.0"/>     <!-- damping- tlmenie  friction- trenie-->
</joint>

<!-- RIGHT -->
<link name="right_wheel_link">
    <visual>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>

        <origin rpy="${PI_2} 0 0" xyz="0 0 0"/>
        <material name="Black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="${PI_2} 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
        <mass value="${wheel_mass}"/>  <!-- preco take tazke???-->
        <origin xyz="0 0 0"/>
            <!--3x3 rotacna zotrvacna matica, Ak je symetricka staci 6 elementov -->
        <cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
    </inertial>
</link>
<gazebo reference="right_wheel_link">
    <turnGravityOff>false</turnGravityOff>
    <material>Gazebo/Black</material>
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
    <fdir1 value="1 0 0"/>

</gazebo>


<joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin rpy="0 0 0" xyz="0 0.2 0"/>
    <axis  xyz="0 1 0" rpy="0  0"/>
        <limit effort="100" velocity="100" />
    <dynamics damping="0.0" friction="0.0"/>
</joint>

<!-- FRONT CASTER-->
<link name="front_caster_link">
    <visual>
        <geometry>
            <sphere radius="${caster_radius}"/>
        </geometry>
        <origin rpy="${-PI_2} 3.1416 0" xyz="0 0 0"/> <!--preco sa pri guly nastavuje rpy-->
        <material name="Black"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${caster_radius}"/>
        </geometry>
        <origin rpy="${-PI_2} 3.1416 0" xyz="0 0 0"/>
    </collision>
    <inertial>
        <mass value="${caster_mass}"/>
        <origin xyz="0 0 0"/>
        <!-- Pocitam zotrvacnost pre PLNU gulu-->
        <sphere_inertia  m="${caster_mass}" r="${caster_radius}" />
    </inertial>
</link>
<gazebo reference="front_caster_link">
    <turnGravityOff>false</turnGravityOff>
    <material>Gazebo/Black</material>
</gazebo>


<joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster_link"/>
    <origin rpy="0 0 0" xyz="0.15 0 -0.044"  />   <!-- preco je v knihe rpy= -1.57 0 0 ?-->
</joint>


<!-- BACK CASTER-->

<link name="back_caster_link">
    <visual>
        <geometry>
            <sphere radius="${caster_radius}"/>
        </geometry>
        <origin rpy="${-PI_2} 3.1416 0" xyz="0 0 0"/>
        <material name="Black"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${caster_radius}"/>
        </geometry>
        <origin rpy="${-PI_2} 3.1416 0" xyz="0 0 0"/>
    </collision>
    <inertial>
        <mass value="${caster_mass}"/>
        <origin xyz="0 0 0"/>
        <sphere_inertia  m="${caster_mass}" r="${caster_radius}" />
    </inertial>


</link>
<gazebo reference="back_caster_link">
    <turnGravityOff>false</turnGravityOff>
    <material>Gazebo/Black</material>
</gazebo>


<joint name="back_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_caster_link"/>
    <origin rpy="0 0 0" xyz="-0.15 0 -0.044"  />   <!--xyz="-0.15 0 -0.045" aj vo Front-->
</joint>

  <!-- hokuyo pozriet vlastnosti-->

<link name="hokuyo_link">
    <visual>
        <geometry>
            <box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <maretial name="Red"/>
    </visual>
    <collision>
        <geometry>
            <box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <material name="Red"/>

</link>

<joint name="hokuyo_joint" type="fixed">
    <parent link="base_link"/>
    <child link="hokuyo_link" />
        <origin xyz="${base_radius-sensor_size/2} 0 ${base_length/2+sensor_size/2}" rpy="0 0 0" />
</joint>

<gazebo reference="hokuyo_link">
    <sensor type="ray" name="head_hokuyo_sensor">
       <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>3.141592654</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>10.0</max>
          <resolution>0.001</resolution>
        </range>

      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>hokuyo_link</frameName>
      </plugin>
    </sensor>
    <material>Gazebo/Red</material>
</gazebo>

  <gazebo>
    <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control">
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <transmission name="left_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="left_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="left_wheel_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </actuator>
  </transmission>

  <transmission name="right_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="right_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="right_wheel_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </actuator>
  </transmission>


</robot>
