<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_drive2">

  <xacro:property name="base_lenght" value="0.4"/>
  <xacro:property name="base_width" value="0.2"/>
  <xacro:property name="base_height" value="0.01"/>
  <xacro:property name="base_mass" value="5.0"/>

  <xacro:property name="wheel_radius" value="0.074"/>
  <xacro:property name="wheel_thickness" value="0.02"/>
  <xacro:property name="wheel_mass" value="3"/>

  <xacro:property name="caster_radius" value="0.0375"/>
  <xacro:property name="caster_mass" value="0.05"/>
  <xacro:property name="caster_offset" value="0.1"/>

  <xacro:include filename="$(find diff_drive_description)/urdf/diff_drive_inertial.urdf.xacro" /> <!--Interial macros-->
  <xacro:include filename="$(find diff_drive_description)/urdf/diff_drive_materials.urdf.xacro" /> <!--Colors (materials)-->
  <xacro:include filename="$(find diff_drive_description)/urdf/diff_drive_gazebo.urdf.xacro" /> <!-- Gazebo plugins -->

  <!-- Creating base -->
  <!-- _____________ -->
  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_lenght} ${base_width} ${base_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black"/>
    </visual>
    <colision>
      <geometry>
        <box size="${base_lenght} ${base_width} ${base_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black"/>
    </colision>
    <xacro:box_inertia m="5" w="${base_lenght}" h="${base_width}" d="0.01"/>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <!-- Main wheels -->
  <!-- ___________ -->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.005"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="${wheel_thickness}"/>
    </link>
    <gazebo reference="${prefix}_wheel">
       <mu1 value="1.0"/>
       <mu2 value="1.0"/>
       <kp value="10000000.0"/>
       <kd value="1.0"/>
       <fdir1 value="1 0 0"/>
     </gazebo>
     <joint name="${prefix}_wheel_joint" type="continuous">
       <parent link="base_link"/>
       <child link="${prefix}_wheel"/>
       <axis xyz="0 1 0" rpy="0 0 0" />
       <origin xyz="0 ${(base_width/2+wheel_thickness/2)*reflect} 0" rpy="0 0 0"/>
       <limit effort="1000" velocity="100" />
       <dynamics damping="0.0" friction="0.0"/>
     </joint>
  </xacro:macro>

  <xacro:wheel prefix="left" reflect="1"/>
  <xacro:wheel prefix="right" reflect="-1"/>

  <!-- Caster wheels -->
  <!-- _____________ -->
  <xacro:macro name="caster" params="prefix reflect" >
    <link name="${prefix}_caster_link">
    	<visual>
    		<geometry>
    			<sphere radius="${caster_radius}"/>
    		</geometry>
    		<origin rpy="0 0 0" xyz="0 0 0"/> <!--preco sa pri guly nastavuje rpy-->
    		<material name="red"/>
    	</visual>
    	<collision>
    		<geometry>
    			<sphere radius="${caster_radius}"/>
    		</geometry>
    		<origin rpy="0 0 0" xyz="0 0 0"/>
    	</collision>
      <xacro:sphere_inertia m="${caster_mass}" r="${caster_radius}"/>
    </link>
    <joint name="${prefix}_caster_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="${prefix}_caster_link"/>
    	<origin rpy="0 0 0" xyz="${caster_offset*reflect} 0 ${-caster_radius}"  />   <!-- preco je v knihe rpy= -1.57 0 0 ?-->
    </joint>
  </xacro:macro>

  <xacro:caster prefix="front" reflect="1"/>
  <xacro:caster prefix="back" reflect="-1"/>

</robot>
